#!/bin/sh

GIT_DIR=$(git rev-parse --git-dir)
BASENAME=$(basename $0)
if [ -f $GIT_DIR/hooks/$BASENAME ]; then
  $GIT_DIR/hooks/$BASENAME $@ || exit $?
fi

scripts/git-clang-format --test --staged
RETCODE=$?

[ $RETCODE -ne 0 ] && [ $RETCODE -ne 1 ] && exit $RETCODE

if [ $RETCODE -eq 1 ]; then
  echo "Some files are not yet formatted.  Run ./format.sh, then try again." >&2
  exit 1
fi

scripts/license
RETCODE=$?

case $RETCODE in
  1)
    echo "Some files have been modified for licensing and need to be staged." >&2
    ;;
  2)
    echo "Some files require additional attention for licensing." >&2
    ;;
esac

[ $RETCODE -ne 0 ] && exit $RETCODE

exit 0
