%define parse.error verbose
%defines
%language "c++"
%locations
%name-prefix "frma"

%param {frma::FormaParserTag *tag}

%code requires {
#include "ast.hpp"
#include "parserTag.hpp"
}

%code provides {
#define YYSTYPE frma::parser::semantic_type
#define YYSTRIM($$) if (!$$->rooted()) delete $$;
#undef yylex


int frmalex(YYSTYPE *, frma::location *, void *);

static int yylex(YYSTYPE *yylval, frma::location *yylloc, frma::FormaParserTag *tag) {
  return frmalex(yylval, yylloc, tag->scan);
}
}

%union {
  frma::FormaAST *    _ast;
  frma::FormaPrims *  _prims;
  frma::FormaPrim *   _prim;
  frma::FormaGroup *  _group;
}

%destructor { if (!($$->rooted() || tag->prims == $$)) delete $$; } <_prims>;
%destructor { YYSTRIM($$); } <_prim>;
%destructor { YYSTRIM($$); } <_group>;

%token Comment

%token LParen   "("
%token RParen   ")"
%token LBracket "["
%token RBracket "]"
%token LBrace   "{"
%token RBrace   "}"

%token <_prim> RawBlock
%token <_prim> Operator
%token <_prim> Identifier
%token <_prim> PPDirective
%token <_prim> Number
%token <_prim> SQLiteral
%token <_prim> DQLiteral

%type <_prims> Input
%type <_prims> PrimariesOpt
%type <_prims> Primaries
%type <_prim>  Primary
%type <_group> PGroup
%type <_group> KGroup
%type <_group> CGroup

%start Input

%initial-action {
  @$.begin.filename = @$.end.filename = &tag->filename();
}

%%
Input: PrimariesOpt { $$ = $1; tag->prims = $1; };

PrimariesOpt:
  %empty    { $$ = new FormaPrims(nullptr); } |
  Primaries { $$ = $1; };

Primaries:
  Primary                       { $$ = new FormaPrims($1); } |
  Primaries[init] Primary[prim] { $$ = new FormaPrims($init, $prim); };

Primary:
  PGroup      { $$ = new FormaPrim($1); } |
  KGroup      { $$ = new FormaPrim($1); } |
  CGroup      { $$ = new FormaPrim($1); } |
  RawBlock    { $$ = $1; } |
  Identifier  { $$ = $1; } |
  PPDirective { $$ = $1; } |
  Number      { $$ = $1; } |
  SQLiteral   { $$ = $1; } |
  DQLiteral   { $$ = $1; } |
  Operator    { $$ = $1; };

PGroup: "(" PrimariesOpt[prims] ")" { $$ = new FormaGroup(FormaGroup::PGroup, $prims); };
KGroup: "[" PrimariesOpt[prims] "]" { $$ = new FormaGroup(FormaGroup::KGroup, $prims); };
CGroup: "{" PrimariesOpt[prims] "}" { $$ = new FormaGroup(FormaGroup::CGroup, $prims); };
%%

void frma::parser::error(const frma::location &loc, const std::string &msg) {
  tag->error(loc, msg);
}
